### ISSUE TITLE
[dev] w wyszukiwarce nie ma opisów i obrazków 

### ISSUE THREAD

**Issue by rysson** [kpl-addons/plugin.video.kpl.tvp#10]
Prace remontowe:
- w wyszukiwarce (to co robił H) nie ma opisów i obrazków

**Comment by heppenowski** [comment]
commit [`b5a3ee91de716f56a49aec75c79d5caa77a31484`](https://github.com/kpl-addons/plugin.video.kpl.tvp/commit/b5a3ee91de716f56a49aec75c79d5caa77a31484) rozwiązuje te braki
