### ISSUE TITLE
TVP Nauka

### ISSUE THREAD

**Issue by Adrianoo02** [kpl-addons/plugin.video.kpl.tvp#11]
Witam. Niestety coś się podziało z TVP Nauka, w oficjalnym TVP GO kanał działa.

**Comment by praspp** [comment]
K19.4, wtyczka v.0.1.5 - TVP Nauka u mnie dziala bez problemu.

**Comment by DenDyGH** [comment]
W ustawieniach wtyczki jaką masz wybraną jakość strumienia?
Spróbuj na domyślnej lub ręcznej.

**Comment by Adrianoo02** [comment]
Mam Kodi 19.4 , wtyczka v. 1.3.9 , wszystkie kanały z TVP GO działają oprócz tego, po prostu nie wczytuje się. W ustawieniach InputStream Adaptive mam Ręcznie wybieraj wszystkie strumienie, po wybraniu innej opcji nadal ten kanał nie działa. 
Na telefonie jest tak samo.

**Comment by praspp** [comment]
@Adrianoo02 Otwierasz zgłoszenie dla wtyczki plugin.video.kpl.tvp [TVP (LIbka)], a po 11h okazuje się, że masz problem z wtyczką plugin.video.tvpgo [TVP GO]. To dwie różne wtyczki. Issue należy otworzyć tu:
 https://github.com/kpl-addons/plugin.video.tvpgo/issues

a wczśniej zapoznać się z tym komunikatem:

https://github.com/kpl-addons/plugin.video.tvpgo#ta-wersja-wtyczki-nie-b%C4%99dzie-aktualizowana-now%C4%85-wersj%C4%99-znajdziesz-tutaj-httpsgithubcomkpl-addonspluginvideokpltvp

Sprawdziłem odtwarzanie kanału TVP Nauka na wtyczce TVP GO v1.3.9 i Kodi 19.4. Odtwarzanie ww kanału, jak i innych działa bez problemu.

Jeśli nadal oczekujesz rozwiązania problemu, to wygeneruj i załącz logi np  wg. tej instrukcji:
https://forum.kodiwpigulce.pl/showthread.php?tid=2478

**Comment by praspp** [comment]
@Adrianoo02 Wprowadź we wtyczce ustawienia timeshift jak na screenie i sprawdź odtwarzanie TVP Nauka. Powinno działać.

![firetv_2022-11-22_16_24_34.jpg](https://user-images.githubusercontent.com/62591068/203354153-345efae9-fa15-49e0-84e4-f86d3151be62.jpg)

**Comment by Cinek77** [comment]
Weźcie to usuńcie albo naprawcie.
@praspp piszesz że u Ciebie działa bez problemu. 
A później się okazuje że
Bez ustawionej stałej wartości time shift (np 720 min.) odtwarzanie live TVP Nauka nie działa.

**Comment by Adrianoo02** [comment]
@praspp Teraz działa na tych ustawieniach. Sorki że nie pisałem pod tą wtyczką ale problem właściwie występował na obu, ale najciekawsze jest to że pojawił się kilka dni temu a nic nie ruszałem, ani na kompie ani na telefonie. Wszystkie pozostałe z TVP GO działały jak zawsze dobrze tylko gdzieś z tym TVP Nauka pojawił się ten problem (myślałem, że coś oni pozmieniali). Najważniejsze że działa, dzięki za te ustawienia :)
