### ISSUE TITLE
Problem z rubryka "Live TV"

### ISSUE THREAD

**Issue by matbla77** [kpl-addons/plugin.video.kpl.tvp#12]
Halo,

Jest problem z rubryka "Live TV", jest ona bardzo powolna. :(

TVP 3 Warszawa dziala tez bardzo powoli.

**Comment by DenDyGH** [comment]
U mnie wchodzi szybko, TVP3 Warszawa również działa szybko i sprawnie.
Jaką masz jakość wybraną w ustawieniach w tyczki? Spróbuj na domyślnej.

**Comment by matbla77** [comment]
> U mnie wchodzi szybko, TVP3 Warszawa również działa szybko i sprawnie. Jaką masz jakość wybraną w ustawieniach w tyczki? Spróbuj na domyślnej.

Mam caly czas na domyślnej jakośći
